/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author sdews
 */
public class FrmMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMain.class.getName());

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuMovimentacao = new javax.swing.JMenu();
        jMenuOpcoes = new javax.swing.JMenu();
        jMenuItemCategoria = new javax.swing.JMenu();
        jMenuItemCategoriaAdd = new javax.swing.JMenuItem();
        jMenuItemCategoriaAlterar = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenu();
        jMenuItemProdutoAdd = new javax.swing.JMenuItem();
        jMenuItemProdutoAlterar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de estoque");

        jMenuMovimentacao.setText("Movimentação");
        jMenuBar.add(jMenuMovimentacao);

        jMenuOpcoes.setText("Opções");

        jMenuItemCategoria.setText("Categoria");

        jMenuItemCategoriaAdd.setText("Adicionar");
        jMenuItemCategoria.add(jMenuItemCategoriaAdd);

        jMenuItemCategoriaAlterar.setText("Alterar");
        jMenuItemCategoria.add(jMenuItemCategoriaAlterar);

        jMenuOpcoes.add(jMenuItemCategoria);

        jMenuItemProduto.setText("Produto");

        jMenuItemProdutoAdd.setText("Adicionar");
        jMenuItemProdutoAdd.addActionListener(this::jMenuItemProdutoAddActionPerformed);
        jMenuItemProduto.add(jMenuItemProdutoAdd);

        jMenuItemProdutoAlterar.setText("Alterar");
        jMenuItemProduto.add(jMenuItemProdutoAlterar);

        jMenuOpcoes.add(jMenuItemProduto);

        jMenuBar.add(jMenuOpcoes);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemProdutoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoAddActionPerformed
        // TODO add your handling code here:
        FrmAddProduto object = new FrmAddProduto();
        object.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutoAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuItemCategoria;
    private javax.swing.JMenuItem jMenuItemCategoriaAdd;
    private javax.swing.JMenuItem jMenuItemCategoriaAlterar;
    private javax.swing.JMenu jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemProdutoAdd;
    private javax.swing.JMenuItem jMenuItemProdutoAlterar;
    private javax.swing.JMenu jMenuMovimentacao;
    private javax.swing.JMenu jMenuOpcoes;
    // End of variables declaration//GEN-END:variables
}
